### PR TITLE
Added currency converter

### PR DESCRIPTION
**Pull request by Roshaen**
## Assigned Issue Number ? { if does not exist then create one }
#007

## Language Opted ?
HTML/CSS/Javascript

## Number of files added or updated ?
3

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've referred the correct issue number.
- [x] I've fill up this entire template correctly.

### CODE REVIEW

**Review by Arsenic-ATG — APPROVED** [review]

**Comment by Arsenic-ATG** [comment]
@Roshaen thanks for the contribution 🏅

**Comment by Arsenic-ATG** [comment]
@Roshaen it would be awesome if you also add a readme file in the automation explaining what is it and how to use it (although it is super intuitive but will still improvise the overall appeal of the automation), I didn't think this issue was serious enough to stop merging so commenting here instead.

**Comment by Roshaen** [comment]
@Arsenic-ATG Nice collections of automation🙂
Really enjoyed contributing👍

**Comment by Arsenic-ATG** [comment]
Glad you liked it 😀

**Pull request merged**
